module.exports = [
	`What weird food combinations do you really enjoy?`,
	`What social stigma does society need to get over?`,
	`What food have you never eaten but would really like to try?`,
	`What’s something you really resent paying for?`,
	`What would a world populated by clones of you be like?`,
	`Do you think that aliens exist?`,
	`What are you currently worried about?`,
	`Where are some unusual places you’ve been?`,
	`Where do you get your news?`,
	`What are some red flags to watch out for in daily life?`,
	`What movie can you watch over and over without ever getting tired of?`,
	`When you are old, what do you think children will ask you to tell stories about?`,
	`If you could switch two movie characters, what switch would lead to the most inappropriate movies?`,
	`What inanimate object would be the most annoying if it played loud upbeat music while being used?`,
	`When did something start out badly for you but in the end, it was great?`,
	`How would your country change if everyone, regardless of age, could vote?`,
	`What animal would be cutest if scaled down to the size of a cat?`,
	`If your job gave you a surprise three day paid break to rest and recuperate, what would you do with those three days?`,
	`What’s wrong but sounds right?`,
	`What’s the most epic way you’ve seen someone quit or be fired?`,
	`If you couldn’t be convicted of any one type of crime, what criminal charge would you like to be immune to?`,
	`What’s something that will always be in fashion, no matter how much time passes?`,
	`What actors or actresses play the same character in almost every movie or show they do?`,
	`In the past people were buried with the items they would need in the afterlife, what would you want buried with you so you could use it in the afterlife?`,
	`What’s the best / worst practical joke that you’ve played on someone or that was played on you?`,
	`Who do you go out of your way to be nice to?`,
	`Where do you get most of the decorations for your home?`,
	`What food is delicious but a pain to eat?`,
	`Who was your craziest / most interesting teacher`,
	`What “old person” things do you do?`,
	`What was the last photo you took?`,
	`What is the most amazing slow motion video you’ve seen?`,
	`Which celebrity do you think is the most down to earth?`,
	`What would be the worst thing to hear as you are going under anesthesia before heart surgery?`,
	`What’s the spiciest thing you’ve ever eaten?`,
	`What’s the most expensive thing you’ve broken?`,
	`What obstacles would be included in the World’s most amazing obstacle course?`,
	`What makes you roll your eyes every time you hear it?`,
	`What do you think you are much better at than you actually are?`,
	`Should kidneys be able to be bought and sold?`,
	`What’s the most creative use of emojis you’ve ever seen?`,
	`When was the last time you got to tell someone “I told you so.”?`,
	`What riddles do you know?`,
	`What’s your cure for hiccups?`,
	`What invention doesn’t get a lot of love, but has greatly improved the world?`,
	`What’s the most interesting building you’ve ever seen or been in?`,
	`What mythical creature do you wish actually existed?`,
	`What are your most important rules when going on a date?`,
	`How do you judge a person?`,
	`If someone narrated your life, who would you want to be the narrator?`,
	`What was the most unsettling film you’ve seen?`,
	`What unethical experiment would have the biggest positive impact on society as a whole?`,
	`When was the last time you were snooping, and found something you wish you hadn’t?`,
	`Which celebrity or band has the worst fan base?`,
	`What are you interested in that most people aren’t?`,
	`If you were given a PhD degree, but had no more knowledge of the subject of the degree besides what you have now, what degree would you want to be given to you?`,
	`What smartphone feature would you actually be excited for a company to implement?`,
	`What’s something people don’t worry about but really should?`,
	`What movie quotes do you use on a regular basis?`,
	`Do you think that children born today will have better or worse lives than their parents?`,
	`What’s the funniest joke you know by heart?`,
	`When was the last time you felt you had a new lease on life?`,
	`What’s the funniest actual name you’ve heard of someone having?`,
	`Which charity or charitable cause is most deserving of money?`,
	`What TV show character would it be the most fun to change places with for a week?`,
	`What was cool when you were young but isn’t cool now?`,
	`If you were moving to another country, but could only pack one carry-on sized bag, what would you pack?`,
	`What’s the most ironic thing you’ve seen happen?`,
	`If magic was real, what spell would you try to learn first?`,
	`If you were a ghost and could possess people, what would you make them do?`,
	`What goal do you think humanity is not focused enough on achieving?`,
	`What problem are you currently grappling with?`,
	`What character in a movie could have been great, but the actor they cast didn’t fit the role?`,
	`What game have you spent the most hours playing?`,
	`What’s the most comfortable bed or chair you’ve ever been in?`,
	`What’s the craziest conversation you’ve overheard?`,
	`What’s the hardest you’ve ever worked?`,
	`What movie, picture, or video always makes you laugh no matter how often you watch it?`,
	`What artist or band do you always recommend when someone asks for a music recommendation?`,
	`If you could have an all-expenses paid trip to see any famous world monument, which monument would you choose?`,
	`If animals could talk, which animal would be the most annoying?`,
	`What’s the most addicted to a game you’ve ever been?`,
	`What’s the coldest you’ve ever been?`,
	`Which protagonist from a book or movie would make the worst roommate?`,
	`Do you eat food that’s past its expiration date if it still smells and looks fine?`,
	`What’s the most ridiculous thing you have bought?`,
	`What’s the funniest comedy skit you’ve seen?`,
	`What’s the most depressing meal you’ve eaten?`,
	`What tips or tricks have you picked up from your job / jobs?`,
	`What outdoor activity haven’t you tried, but would like to?`,
	`What songs hit you with a wave of nostalgia every time you hear them?`,
	`What’s the worst backhanded compliment you could give someone?`,
	`What’s the most interesting documentary you’ve ever watched?`,
	`What was the last song you sang along to?`,
	`What’s the funniest thing you’ve done or had happen while your mind was wandering?`,
	`What app can you not believe someone hasn’t made yet?`,
	`When was the last time you face palmed?`,
	`If you were given five million dollars to open a small museum, what kind of museum would you create?`,
	`Which of your vices or bad habits would be the hardest to give up?`,
	`What really needs to be modernized?`,
	`When was the last time you slept more than nine hours?`,
	`How comfortable are you speaking in front of large groups of people?`,
	`What’s your worst example of procrastination?`,
	`Who has zero filter between their brain and mouth?`,
	`What was your most recent lie?`,
	`When was the last time you immediately regretted something you said?`,
	`What would be the best thing you could reasonably expect to find in a cave?`,
	`What did you think was going to be amazing but turned out to be horrible?`,
	`What bit of trivia do you know that is very interesting but also very useless?`,
	`What’s the silliest thing you’ve seen someone get upset about?`,
	`What animal or plant do you think should be renamed?`,
	`What was the best thing that happened to you today?`,
	`As a child, what did you think would be awesome about being an adult, but isn’t as awesome as you thought it would be?`,
	`When’s censorship warranted?`,
	`What’s the most boring super hero you can come up with?`,
	`What would be some of the downsides of certain superpowers?`,
	`What word is a lot of fun to say?`,
	`What current trend do you hope will go on for a long time?`,
	`What actors or actresses can’t play a different character because they played their most famous character too well?`,
	`Where’s your go to restaurant for amazing food?`,
	`What’s something that all your friends agree on?`,
	`What’s your best story from a wedding?`,
	`What languages do you wish you could speak?`,
	`What’s the most pleasant sounding accent?`,
	`What’s something that everyone, absolutely everyone, in the entire world can agree on?`,
	`What country is the strangest?`,
	`What’s the funniest word in the English language?`,
	`What’s some insider knowledge that only people in your line of work have?`,
	`Who do you wish you could get back into contact with?`,
	`How do you make yourself sleep when you can’t seem to get to sleep?`,
	`If people receive a purple heart for bravery, what would other color hearts represent?`,
	`What are some of the best vacations you’ve had?`,
	`If there was a book of commandments for the modern world, what would some of the rules be?`,
	`What’s the craziest video you’ve ever seen?`,
	`What’s your “Back in my day, we…”?`,
	`If you could know the truth behind every conspiracy, but you would instantly die if you hinted that you knew the truth, would you want to know?`,
	`What animal would be the most terrifying if it could speak?`,
	`What’s the worst hairstyle you’ve ever had?`,
	`What habit do you have now that you wish you started much earlier?`,
	`If you were given one thousand acres of land that you didn’t need to pay taxes on but couldn’t sell, what would you do with it?`,
	`What about the opposite sex confuses you the most?`,
	`When was the last time you yelled at someone?`,
	`What’s the opposite of a koala?`,
	`What kinds of things do you like to cook or are good at cooking?`,
	`What life skills are rarely taught but extremely useful?`,
	`What movie universe would be the worst to live out your life in?`,
	`If you could hack into any one computer, which computer would you choose?`,
	`Who do you feel like you know even though you’ve never met them?`,
	`What’s the most ridiculous animal on the planet?`,
	`What’s the worst thing you’ve eaten out of politeness?`,
	`What’s the most historic thing that has happened in your lifetime?`,
	`What happens in your country regularly that people in most countries would find strange or bizarre?`,
	`What has been blown way out of proportion?`,
	`When was a time you acted nonchalant but were going crazy inside?`,
	`What’s about to get much better?`,
	`What are some clever examples of misdirection you’ve seen?`,
	`What’s your funniest story involving a car?`,
	`What would be the click-bait titles of some popular movies?`,
	`If you built a themed hotel, what would the theme be and what would the rooms look like?`,
	`What scientific discovery would change the course of humanity overnight if it was discovered?`,
	`Do you think that humans will ever be able to live together in harmony?`,
	`What would your perfect bar look like?`,
	`What’s the scariest non-horror movie?`,
	`What’s the most amazing true story you’ve heard?`,
	`What’s the grossest food that you just can’t get enough of?`,
	`What brand are you most loyal to?`,
	`What’s the most awkward thing that happens to you on a regular basis?`,
	`If you had to disappear and start a whole new life, what would you want your new life to look like?`,
	`What movie or book do you know the most quotes from?`,
	`What was one of the most interesting concerts you’ve been to?`,
	`Where are you not welcome anymore?`,
	`What do you think could be done to improve the media?`,
	`What’s the most recent show you’ve binge watched?`,
	`What’s the worst movie trope?`,
	`What’s a common experience for many people that you’ve never experienced?`,
	`What are some misconceptions about your hobby?`,
	`What’s the smartest thing you’ve seen an animal do?`,
	`What’s the most annoying noise?`,
	`What’s your haunted house story?`,
	`What did you Google last?`,
	`What’s the dumbest thing someone has argued with you about?`,
	`If money and practicality weren’t a problem, what would be the most interesting way to get around town?`,
	`What’s the longest rabbit hole you’ve been down?`,
	`What’s the saddest scene in a movie or TV series?`,
	`What’s the most frustrating product you own?`,
	`What inconsequential super power would you like to have?`,
	`What qualities do all your friends have in common?`,
	`What odd smell do you really enjoy?`,
	`What’s the coolest animal you’ve seen in the wild?`,
	`What’s the best lesson you’ve learned from a work of fiction?`,
	`What food do you crave most often?`,
	`Who in your life has the best / worst luck?`,
	`What fashion trend makes you cringe or laugh every time you see it?`,
	`What’s your best story of you or someone else trying to be sneaky and failing miserably?`,
	`Which apocalyptic dystopia do you think is most likely?`,
	`If you had a HUD that showed three stats about any person you looked at, what three stats would you want it to show?`,
	`What’s the funniest thing you’ve seen a kid do?`,
	`What’s your secret talent?`,
	`What’s the best way you or someone you know has gotten out of a ticket / trouble with the law?`,
	`Tear gas makes people cry and laughing gas makes people giggle, what other kinds of gases do you wish existed?`,
	`What’s the most beautiful beach you’ve been to?`,
	`What’s the most anxiety inducing thing you do on a regular basis?`,
	`What’s something that everyone agrees we should change, but somehow it never changes?`,
	`What trend are you tired of?`,
	`What’s incredibly cheap and you would pay way more for?`,
	`What’s your grossest bug story?`,
	`What would the adult version of an ice-cream truck sell and what song would it play?`,
	`What company do you despise?`,
	`When was the most inappropriate time you busted out in laughter?`,
	`What would be an accurate tag line for each month?`,
	`What’s the most overrated product out on the market?`,
	`What word do you always misspell?`,
	`What naps are the most satisfying?`,
	`What’s the weirdest thing you’ve found lying on the ground / side of the road?`,
	`What’s the funniest TV show you’ve ever seen?`,
	`What’s the most embarrassing story from your childhood?`,
	`What animal is the most majestic?`,
	`What’s something that everyone knows is true, but we don’t like to admit it?`,
	`What’s the weirdest text or email you’ve gotten?`,
	`What always cheers you up when you think about it?`,
	`What sport could you play the longest in a televised game, without anyone discovering you aren’t a professional athlete?`,
	`If you could talk to animals and they would understand you, but you couldn’t understand them, what would you do with that power?`,
	`What’s the most boring sport, and what would you do to make it more exciting?`,
	`What’s the creepiest tech out there?`,
	`Who did you use to look up to, but they screwed up and you lost faith in them?`,
	`What’s fine in small numbers but terrifying in large numbers?`,
	`Do you like things to be carefully planned or do you prefer to just go with the flow?`,
	`What animal would you most like to eat?`,
	`What fictional characters have you had a crush on over the years?`,
	`What would the box with all your hopes and dreams inside look like?`,
	`What was the worst shopping experience you’ve ever had?`,
	`What story you’ve heard has stayed with you and always disturbs you every time you think about it?`,
	`What was the most important appointment or deadline you missed?`,
	`If you were a clown themed super hero, what powers would you have?`,
	`If you could airdrop anything you want, worth two million dollars or less, anywhere you want, what would you airdrop and where would you airdrop it?`,
	`If you lived in a virtual reality world of your own creation, what would it look like?`,
	`What escalated very quickly?`,
	`What two things are terrible when separate but great when you put them together?`,
	`What did you believe for way too long as a child?`,
	`What big event do you think will happen soon that most people aren’t expecting?`,
	`What still makes you cringe when you think back on it?`,
	`What current trend makes no sense to you?`,
	`If you owned a restaurant, what kind of food would it serve?`,
	`Which celebrity is the most likely to have a collection of canes that are just for show?`,
	`What’s the weirdest crush you’ve had?`,
	`What do a lot of people have very strong opinions about, even though they know very little about it?`,
	`What’s your go to casino game?`,
	`An epic feast is held in your honor, what’s on the table?`,
	`What’s your favorite holiday movie?`,
	`Who is the most manipulative person you’ve ever met?`,
	`Who is the most creative person you know?`,
	`What’s the funniest pick up line you’ve heard?`,
	`What seemingly innocent question makes you think “It’s a trap!”?`,
	`How ambitious are you?`,
	`What did you like / dislike about where you grew up?`,
	`What elements of pop culture will be forever tied in your mind to your childhood?`,
	`What’s your good luck charm?`,
	`What’s legal now, but probably won’t be in 25 years?`,
	`Would you want the ability to hear the thoughts of people near you if you couldn’t turn the ability off?`,
	`When was the last time you stayed up through the entire night?`,
	`What’s something that people think makes them look cool, but actually has the opposite effect?`,
	`What’s the oldest thing you own?`,
	`What has someone borrowed but never given back?`,
	`Where is the best place you’ve been for taking walks?`,
	`If cartoon physics suddenly replaced real physics, what are some things you would want to try?`,
	`What from the present will withstand the test of time?`,
	`Who in your life is the worst at using technology?`,
	`What’s the weirdest conversation you’ve eavesdropped on?`,
	`What just around the corner tech are you eager to get your hands on?`,
	`What was the darkest movie you’ve ever seen?`,
	`What do you do when you hear something fall in the middle of the night while you are in bed?`,
	`What outfit could you put together from clothes you own to get the most laughs?`,
	`What’s the most disgusting sounding word in the English language?`,
	`What was ruined because it became popular?`,
	`What outdated slang do you use on a regular basis?`,
	`What was the biggest realization you had about yourself?`,
	`What’s your best example of easy come, easy go?`,
	`What small change greatly improves a person’s appearance?`,
	`What topic could you spend hours talking about?`,
	`What happens regularly that would horrify a person from 100 years ago?`,
	`What do a lot of people hope will happen but is just not going to happen?`,
	`What’s the weirdest thing that has happened to you while working at your job?`,
	`What questions would you like to ask a time traveler from 200 years in the future?`,
	`Which way should toilet paper hang, over or under?`,
	`What’s the most physically painful thing you’ve ever experienced?`,
	`What horror story do you have from a job you’ve had?`,
	`What’s the most rage inducing game you’ve ever played?`,
	`What’s the biggest overreaction you’ve ever seen?`,
	`What are some of the most common misconceptions?`,
	`What job doesn’t exist now but will exist in the future?`,
	`What awful movie do you love?`,
	`What normally delicious food gets ruined when you wrap it in a tortilla?`,
	`What’s your best example of fake it till you make it?`,
	`What were you completely certain of until you found out you were wrong?`,
	`What’s something commonly done that gets progressively weirder the more you think about it?`,
	`What’s the cutest thing you can imagine? Something so cute it’s almost painful.`,
	`If you were given unlimited resources, how would you lure the worst of humanity into one stadium at the same time?`,
	`What do you think about when you hear the word “classy”?`,
	`What near future predictions do you have?`,
	`What do you need help with most often?`,
	`What piece of “art” would you create if you had to pretend to be an artist and submit something to a gallery?`,
	`What do you do to make the world a better place?`,
	`What’s the best and worst thing about the country you are from?`,
	`If you were in charge renaming things so that their names would be more accurate, what names would you come up with?`,
	`What’s better broken than whole?`,
	`What values are most important to you?`,
	`What’s the best sandwich you’ve ever had?`,
	`What’s the worst thing you ate from a fast food restaurant?`,
	`What’s something that I don’t know?`,
	`What profession doesn’t get enough credit or respect?`,
	`What memory of yours feels real but is most likely false?`,
	`What’s your “and then it got worse” story?`,
	`What was the most amazing physical feat you’ve managed to pull off?`,
	`What’s the most annoying thing about the social media platform you use most often?`,
	`If you were hired to show tourists what life is really like where you live, what would you show them / have them do?`,
	`What would be the most unsettling thing to keep occasionally finding around your house?`,
	`What nicknames do you have for people in your life?`,
	`What does the opposite sex do that you wish that you could do, but it’s not anatomically feasible or it’s socially frowned upon?`,
	`How much do you plan / prepare for the future?`,
	`What do you hate most and love most about your car?`,
	`What weird potato chip flavor that doesn’t exist would you like to try?`,
	`What’s the silliest thing you’ve convinced someone of?`,
	`How much do you think names affect the outcomes of people’s lives?`,
	`What product or service is way more expensive than it needs to be?`,
	`What’s the shadiest thing you’ve seen someone do?`,
	`What was the last situation where some weird stuff went down and everyone acted like it was normal, and you weren’t sure if you were crazy or everyone around you was crazy?`,
	`What did you eat so much of that now you hate it?`,
	`What are some of the dumbest lyrics you’ve heard in a song?`,
	`Where’s the line between soup and cereal?`,
	`What word do you always mispronounce?`,
	`What do you think you do better than 90% of people?`,
	`What would be the worst food to be liquefied and drunk through a straw?`,
	`What’s the weirdest thing about modern life that people just accept as normal?`,
	`How much of your body would you cybernetically enhance if you could?`,
	`If you wanted to slowly drive a roommate insane using only notes, what kind of notes would you leave around the house?`,
	`If you had a giraffe that you needed to hide, where would you hide it?`,
	`What’s the clumsiest thing you’ve done?`,
	`What songs do you only know the chorus to?`,
	`Think of a brand, now what would an honest slogan for that brand be?`,
	`What’s something common from your childhood that will seem strange to future generations?`,
	`What’s the most amazing place in nature you’ve been?`,
	`What’s quickly becoming obsolete?`,
	`Where is the most uncomfortable place you have ever slept?`,
	`What’s the most annoying animal you’ve encountered?`,
	`What’s your best example of correlation not equaling causation?`,
	`In what situations, do you wish you could throw down a smoke bomb and disappear?`,
	`When was the last time you were hopelessly lost?`,
	`What songs do you feel compelled to sing along with when you hear them, even if you don’t totally know all the words?`,
	`What product do you wish a company would make a “smart” version of?`,
	`What two films would you like to combine into one?`,
	`What’s are some of your Pavlovian responses?`,
	`What’s the best thing you’ve got going on in your life at the moment?`,
	`What incredibly common thing have you never done?`,
	`What has taken you the longest to get good or decent at?`,
	`What food do you love that a lot of people might find a little odd?`,
	`If you could start a charity, what would it be for?`,
	`What was the funniest thing you’ve seen recently online?`,
	`What are some of your favorite games to play?`,
	`What takes a lot of time but is totally worth it?`,
	`What is the most amazing fact you know?`,
	`What website or app doesn’t exist, but you really wish it did?`,
	`What’s your favorite type of day? (weather, temp, etc.)`,
	`What is the most clever or funniest use of advertising you’ve seen?`,
	`How into self-improvement are you?`,
	`When someone finds out what you do, or where you are from, what question do they always ask you?`,
	`Are you more productive at night or in the morning? Do you think it’s possible to change and get used to another schedule?`,
	`What scene in a movie always gives you goosebumps every time you watch it?`,
	`What topic could you give a 20-minute presentation on without any preparation?`,
	`What’s something that a lot of people are missing out on because they don’t know about it?`,
	`What are some of your guilty pleasures?`,
	`Who is the most interesting person you’ve met and talked with?`,
	`What has really taken a toll on you?`,
	`How did you spend the money from your very first job?`,
	`What do you wish someone taught you a long time ago?`,
	`Do you think you rely too heavily on your phone? Why or why not?`,
	`How could carousels be spiced up so they are more exciting?`,
	`What’s your favorite car that you’ve owned?`,
	`What subjects should be taught in school but aren’t?`,
	`What’s the biggest vehicle you’ve driven?`,
	`What songs would be played on a loop in hell?`,
	`What rule do you wish they would introduce into your favorite sport?`,
	`What kind of challenges are you facing these days?`,
	`What do you highly recommend to most people you meet?`,
	`Do you think you have a pretty good work-life balance? Why or why not?`,
	`What was the last thing you were really excited about?`,
	`What’s your best “my coworkers are crazy” story?`,
	`What does your perfect breakfast look like?`,
	`What are some of your favorite holiday traditions that you did while growing up?`,
	`If you could choose your dreams, what would you prefer to dream about?`,
	`Would you ride in a zeppelin if given a chance?`,
	`What’s something that was once important but is now becoming less and less relevant?`,
	`What tells you the most about a person?`,
	`When is the most interesting period in history?`,
	`What is the best pair of shoes you have owned?`,
	`What book had the most significant impact on you?`,
	`Where’s your favorite place to nap?`,
	`What is the best event you’ve attended?`,
	`What do you buy way more of than most people?`,
	`What do you rebel against?`,
	`What well-known person does the most good for the world?`,
	`What’s your favorite food combination?`,
	`What’s the weirdest way you have met someone?`,
	`What’s the most amazing natural occurrence you’ve witnessed?`,
	`How did you get that scar of yours?`,
	`What do you wish was illegal?`,
	`If someone came up to you and said “Hey, do that thing you do!”, what thing would pop into your head first?`,
	`Who is the most intelligent or creative person you know?`,
	`What wastes the most time in your day to day life?`,
	`What’s a problem you have, that might be entirely unique to you?`,
	`What company or brand did you love until they betrayed your trust?`,
	`Would you ever try space tourism, if you had the money for it?`,
	`What’s the most annoying machine you must deal with regularly?`,
	`What are you grateful for?`,
	`What hobby would you be a lot of fun to get into?`,
	`What do you resent paying for most?`,
	`What pets did you have growing up?`,
	`What’s the best or worst prank you’ve played on someone?`,
	`What was the scariest movie you’ve seen?`,
	`What motivates you?`,
	`Where are five places you really want to visit before you die?`,
	`What’s the best location to fully enjoy a good cup of coffee?`,
	`How handy are you when it comes to fixing things?`,
	`What skill or talent would you most like to learn?`,
	`What weird thing do you have nostalgia for?`,
	`What works of art have really made an impression on you?`,
	`What culture would you like to learn more about?`,
	`If you were featured on the local news, what would you most likely be on there for?`,
	`What do you wish your phone could do?`,
	`What’s your favorite international food?`,
	`What workers have the worst jobs?`,
	`What kind of physical activities do you like doing?`,
	`Would you rather watch a movie on your TV at home or on the big screen in the theater, and why?`,
	`What assumption you made went hilariously wrong?`,
	`What big problem do you think technology will solve next?`,
	`What fashion trend needs to be brought back?`,
	`How do you think you will be/act when you are old?`,
	`What’s your favorite way to waste time online?`,
	`What’s the longest trip you’ve been on?`,
	`What was something you thought would be easy until you tried it?`,
	`What, in your opinion, is the most amazing animal?`,
	`How into tech are you? Why?`,
	`What is the biggest mistake you’ve made at work?`,
	`Who is the oldest person you know personally? What interesting stories have they told you?`,
	`Who is the funniest person in your family?`,
	`What useless facts do you know?`,
	`What’s your favorite Olympic sport to watch?`,
	`How do you usually get your news?`,
	`What smell do you hate that doesn’t seem to bother other people?`,
	`What’s the most delightful hotel or house you’ve stayed in on vacation?`,
	`What weird quirks did you pick up from your parents?`,
	`What were your favorite television shows when you were growing up?`,
	`What’s the silliest thing you are pretty good at?`,
	`What’s your idea of a great day?`,
	`What are some of the dumbest misadventures you’ve been on?`,
	`What do you want to do when you retire?`,
	`What do you do to unwind after a hard day?`,
	`Who is the most competitive person you know?`,
	`Would you rather spend time with other people or at home alone?`,
	`What are some films that would make it on to your top 50 list of movies?`,
	`What slang are you really happy went out of fashion?`,
	`What music do you put on when you want to get pumped?`,
	`What makes you feel old when you think about it?`,
	`How well do you know your neighbors?`,
	`What’s the best backhanded compliment you’ve heard / can think of on the spot?`,
	`Who is the most interesting stranger you’ve met?`,
	`What was your funniest or worst experience with a dentist?`,
	`What’s the noblest endeavor a person can dedicate their life to?`,
	`What’s your idea of a great party?`,
	`What are some of your favorite scenes from movies?`,
	`What are two of your favorite snacks?`,
	`What’s the biggest adventure you’ve been on?`,
	`Besides war and diplomacy, what would be the best way for countries to settle disputes?`,
	`What household chore do you actually enjoy?`,
	`What is something you do better than most people and something you do worse than most people?`,
	`What TV show are you hooked on or were recently hooked on?`,
	`If you had to lose one of your senses, which would you choose to lose?`,
	`If a new volcano formed and the government had an online contest to see what it would be named, what name would you submit?`,
	`What is the last goal you achieved?`,
	`What was your worst haircut experience?`,
	`Do you prefer pens or pencils? Why?`,
	`What’s the best way to stay young?`,
	`What is the most stressful TV show or movie you watched?`,
	`How good are you at drawing?`,
	`What did your teachers and parents say would be really important when you grew up, but it hasn’t been? `,
	`How do you feel about clowns?`,
	`What is your favorite genre of movie? Why?`,
	`What brands do you love/hate the most?`,
	`What is the weirdest food combination you’ve made and tried?`,
	`What would you change if you were in charge of the company you work for?`,
	`Who has been your most interesting/confusing/annoying neighbor?`,
	`Has there ever been a time when something so amazing or unexpected happened that it literally left you speechless for a time?`,
	`Where’s the most surreal area you been to?`,
	`What are common misconceptions about your job?`,
	`What public spaces do you feel most comfortable in? (Library, bar, park, mall, stadium, etc.)`,
	`What’s the most outdated piece of tech you still use regularly?`,
	`What’s the weirdest food you’ve eaten?`,
	`Who was your favorite teacher?`,
	`What recent trend are you totally on board with?`,
	`What about becoming an adult caught you completely off guard?`,
	`How often do you dance?`,
	`What’s the best cake you’ve ever eaten?`,
	`What kind of art do you appreciate the most?`,
	`What crossed way too far into the uncanny valley for you?`,
	`What’s your favorite thing about the area/city/state you live in?`,
	`What’s the best day you’ve had recently?`,
	`What’s your favorite way to spend time outdoors?`,
	`What does your perfect burger or sandwich have in it?`,
	`What’s the worst advice you’ve been given?`,
	`What’s the strangest name someone you have met had?`,
	`What was something courageous you’ve (in person) seen someone do?`,
	`What card or board games do you like to play?`,
	`What are you best at fixing?`,
	`What movie never gets old no matter how many times you’ve seen it?`,
	`If the universe is just a simulation, what update or patch does it need?`,
	`Where have you traveled to?`,
	`What’s the scariest horror movie or horror book monster?`,
	`What’s the most unique shop or restaurant you’ve been in?`,
	`What hard time in your life left you a better person after it was finished?`,
	`What’s the best sports game you’ve been to?`,
	`What period would be the best to be born in?`,
	`What sport do you wish you knew more about?`,
	`What’s something you’re looking forward to?`,
	`What’s the most creative thing you’ve done?`,
	`What are you hilariously bad at?`,
	`Tell me about a time you were totally out of your element/comfort zone.`,
	`Are you a cat or dog person or neither? Why?`,
	`Who is the most gifted person you know?`,
	`What was your best vacation?`,
	`What do you usually do on your commute to work?`,
	`What was the craziest theme park or fair ride you’ve been on?`,
	`What kind of people do you most enjoy hanging out with?`,
	`What do you think the ideal age to be is?`,
	`What are you kind of snobby about?`,
	`What toy did you hate most as a child?`,
	`What’s your drink of choice? (Either alcoholic or non.)`,
	`If you left your current life behind and ran away to follow your dreams, what would you be doing?`,
	`What food is underrated or underappreciated?`,
	`What’s your favorite line from a book or a movie?`,
	`What is the best thing you have ever bought?`,
	`What catchy jingle or bit of advertising has stuck with you all these years?`,
	`What luxury is totally worth the price?`,
	`What is the most unique or silliest problem you have going on in your life at the moment?`,
	`What could movie theaters do to improve the experience of going there?`,
	`If you were so wealthy you didn’t need to work, what would you do with your time?`,
	`What apps do you use most?`,
	`What is the most tedious and/or the most exciting sport to watch?`,
	`What’s your favorite island that you’ve visited?`,
	`What do you geek out about?`,
	`Besides insects and spiders, what animals annoy you the most?`,
	`What’s your favorite month?`,
	`What’s the best concert you’ve been to and why was it so good?`,
	`What harsh truths do you prefer to ignore?`,
	`Is free will real or just an illusion?`,
	`Is there a meaning to life? If so, what is it?`,
	`Where is the line between art and not art?`,
	`What should be the goal of humanity?`,
	`Does fate exist? If so, do we have free will?`,
	`What does it mean to live a good life?`,
	`Why do we dream?`,
	`Where does your self-worth come from?`,
	`How will humans as a species go extinct?`,
	`Is it possible to live a normal life and not ever tell a lie?`,
	`Does a person’s name influence the person they become?`,
	`Is the meaning of life the same for animals and humans?`,
	`If someone you loved was killed in front of you, but someone created a copy of them that was perfect right down to the atomic level, would they be the same person and would you love them just as much?`,
	`If you could become immortal on the condition you would NEVER be able to die or kill yourself, would you choose immortality?`,
	`What actions in your life will have the longest reaching consequences? How long will those effects be felt?`,
	`How long will you be remembered after you die?`,
	`If a child somehow survived and grew up in the wilderness without any human contact, how “human” would they be without the influence of society and culture?`,
	`How would humanity change if all humans’ life expectancy was significantly increased (let’s say to around 500 years)?`,
	`Where do you find meaning in your life?`,
	`What do you think would be humanity’s reaction to the discovery of extraterrestrial life?`,
	`Will religion ever become obsolete?`,
	`If you could teach everyone in the world one concept, what concept would have the biggest positive impact on humanity?`,
	`Is suffering a necessary part of the human condition? What would people who never suffered be like?`,
	`Does hardship make a person stronger? If so, under what conditions and at what point is it too much hardship? If not, what makes a person stronger?`,
	`Would things get better or worse if humans focused on what was going well rather than what’s going wrong?`,
	`What benefits does art provide society? Does art hurt society in any way?`,
	`How likely do you think it will be that humans will last another 1,000 years without killing ourselves off?`,
	`What do you attribute the biggest successes in your life to? How about your largest failures?`,
	`If freedom is simply being able to do what you want, are animals freer than humans?`,
	`Would you want to know you are going to die before hand or die suddenly without warning?`,
	`Is humanity headed in the right or wrong direction?`,
	`Does the study of philosophy ever lead to answers or simply more questions?`,
	`What is the best way for a person to attain happiness?`,
	`If you had to guess, what do you think would be the most likely way you’ll die?`,
	`Is it better for a person to have a broad knowledge base or a deep knowledge base?`,
	`What is the best way to train people to see the gradients in the world around them instead of just a simplistic “this is good, that is wrong” view of the world?`,
	`Is intelligence or wisdom more useful?`,
	`Which of your beliefs are justified and which ones aren’t?`,
	`What do you contribute back to society?`,
	`What are you going to do with the one life you have?`,
	`Is it more important to help yourself, help your family, help your society, or help the world?`,
	`What life-altering things should every human ideally get to experience at least once in their lives?`,
	`What is the most important goal every person should have?`,
	`Is it better to be a big fish in a small pond or a small fish in a big pond?`,
	`What are you capable of achieving?`,
	`By what standards do you judge yourself?`,
	`Can human nature be changed? Should it be changed?`,
	`How replaceable are you?`,
	`Why don’t we as a species take more advantage of the fact that we have almost infinite knowledge available to us?`,
	`What two questions would you ask to get the most information about who a person truly is?`,
	`Some people believe that if life has no purpose, then there is no reason for living. While others think that if life has no purpose, that frees a person to find/create and follow their own personal purpose. Which is a more valid point of view or are they both equally valid?`,
	`Does absolute power corrupt absolutely?`,
	`Why do we judge ourselves by our intentions but judge others by their actions?`,
	`What activities cause you to feel like you are living life to the fullest?`,
	`Does knowledge have intrinsic value or does it need to have a practical use to have value?`,
	`What would you genetically change about humans to make them a better species?`,
	`How important is play in living a healthy and fulfilling life?`,
	`Where do you think is the most worthwhile place to find meaning in life? Work, family, hobby, religion, philosophy, helping others, all the small miracles, or something else entirely?`,
	`What is the biggest waste of human potential?`,
	`Is a life that focuses on avoiding pain and seeking out pleasure a good and worthwhile life? Why or why not?`,
	`Does jealously have value in driving humans to improve themselves or is it a purely negative emotion?`,
	`What percentage of your life do you feel truly alive? When do you feel that way? How can you feel that way more often?`,
	`What do you think your future self will remember about you now?`,
	`“Know thyself” is an ancient concept going back much further than Socrates and is at the root of much of philosophy. With that in mind, what are the most important things to learn about one’s self or is all self-knowledge equal?`,
	`What do you think existed before the universe was created?`,
	`Is math something that humans created or something we discovered? Is looking at reality mathematically an accurate representation of how things work?`,
	`Is it possible for a human to fathom the true depths of reality and existence?`,
	`If the universe is finite, what would beyond the edge of the universe be like?`,
	`What is the best path to find truth; science, math, art, philosophy, or something else?`,
	`As more and more is being discovered about quantum physics, we become less and less able to comprehend the nature of reality. Is this something temporary and our minds will adapt and begin to understand this new reality or is it possible that the human mind will soon reach its limits of comprehension? If it’s only temporary, is there is a limit to what the human mind can comprehend? If we are reaching our limits, how do we continue to study our reality?`,
	`Is there inherent order in nature or is it all chaos and chance?`,
	`What in life is truly objective and not subjective?`,
	`There has always been something. Before there was something, there was only nothing. Which do you think is more likely?`,
	`Is happiness just chemicals flowing through your brain or something more?`,
	`Why are humans so susceptible to magical thinking?`,
	`If every neuron in a human was accurately simulated in a computer, would it result in human consciousness?`,
	`Is it possible that some animals are self-aware and think about their ability to think?`,
	`How do you define consciousness?`,
	`Is it possible to prove that other people besides yourself have consciousness?`,
	`How conscious do you think animals are?`,
	`Assuming evolution is correct, do you think that if humans went extinct another species as intelligent as humans would evolve? If life exists long enough on a planet, is intelligence and consciousness inevitable?`,
	`Would it be more frightening to discover that humans are the most advanced species in the universe or that we are far from being the most advanced species in the universe?`,
	`How would you define genius?`,
	`There is zero chance that ALL your firmly and dearly held beliefs are true. So, which of your beliefs are most likely to be wrong and which are most liable to be true?`,
	`How much does language affect our thinking?`,
	`Why are humans so confident in beliefs that can’t be proven?`,
	`If all your memories were erased, what kind of person would you be?`,
	`Why do humans have such a strong urge to distract ourselves from the real world?`,
	`What is the benefit of consciousness from an evolutionary stand point?`,
	`Is the concept of “you” continuous or does past “you” continually fade into present and future “you”? In other words, what part of “you” sticks around over time considering that the atoms that make up your body are constantly being replaced and your memories are always changing?`,
	`Is it possible that someone’s genes might affect their political leanings? If no, why not? If so, what would be the ramifications?`,
	`Can rational thought exist without language?`,
	`Would selectively breeding an animal such as a dog based on intelligence, increase its intelligence over time? If so, how intelligent could dogs become? If not, how does intelligence emerge in a species?`,
	`Are there limits to human creativity?`,
	`Why do we resist doing things that we know are good for our well-being while craving things that are detrimental to our well-being?`,
	`Is it be possible for humans to create something completely novel and new that is based on nothing that previously existed? Or is human creativity just rearranging and building on previous ideas?`,
	`If there existed a perfect clone of you, would it also be you? Would it act in exactly the same manner as you (like a mirror) or would it act differently? If it acted differently then would it still be you? At what point would it not be you?`,
	`Would you be able to tell if time had been altered in some way?`,
	`Your perception of the world is just what your brain constructs for you from the signals sent by your senses. Plus, there is a slight delay, so you aren’t even experiencing the simulation in real time. What would it be like if humans could perceive what the world is actually like and do it in real time? Also, what are the ramifications of every single person’s reality being a little different and unique to them?`,
	`If language influences how we perceive color, what other things could languages be changing our perception of?`,
	`Is a sense of humor a byproduct of consciousness or something else entirely?`,
	`Are intelligence and happiness tied together in any way? If you are highly intelligent, is it more likely that you’ll be more, or less happy?`,
	`Human memory has been shown to be incredibly unreliable. With that in mind, how do you know which of your memories are genuine and which have been altered or made up?`,
	`Different people and different organisms perceive reality in vastly different ways. With that in mind, what is real and what is just our perception of reality? Or does every organism live in its own personal reality?`,
	`When, if ever, is taking a human life justified?`,
	`Can animals have morals?`,
	`Without religion would people become more, less, or be equally morally corrupt?`,
	`If humanity was put on trial by an advanced race of aliens, how would you defend humanity and argue for its continued existence?`,
	`What rights does every human have? Do those rights change based on age?`,
	`Do animals have rights and do those rights extend to all animals or do the rights change based on the complexity of the animal?`,
	`Is justice a human construct or is it independent of humans?`,
	`Why do people expect a universe full of randomness to be fair?`,
	`With no laws or rules to influence your behavior, how do you think you would behave?`,
	`What’s the difference between justice and revenge?`,
	`If it was discovered that personality traits were partly genetic and could be removed with gene therapy, would it be ethical to edit out negative character traits that harm others like extreme aggression, compulsive lying, or cruelty?`,
	`If you could press a button and receive a million dollars, but one stranger would die, would you press the button? And if so, how many times?`,
	`What would be the most ethical way to give away five million dollars?`,
	`Are people ethically obligated to improve themselves?`,
	`Is privacy a right?`,
	`At what point is overthrowing a government ethical, considering all the violence a revolution usually entails?`,
	`Can morality ever be objective or is it always subjective? If it can be objective, in what instances? If it’s always subjective, how do we decide whose concept of morality is correct?`,
	`Are intentions or outcomes more important when judging whether actions are moral?`,
	`Should there be limitations on the right to free speech?`,
	`If it was discovered that most animals were conscious of their existence and eventual death, what would be the ramifications of that discovery?`,
	`Should euthanasia be legal? Why or why not?`,
	`If scientists could accurately predict who was more likely to commit crimes, what should society do with that information?`,
	`Do business owners have the right to refuse service to customers?`,
	`If babies are considered innocent, when do people cease to be innocent?`,
	`Why do humans often associate beauty with morality?`,
	`If you can save another’s life and don’t because doing so would break the law, are you ethically justified in your decision?`,
	`Are all individuals morally obligated to save another person’s life if they are able? What if that person lives in another country?`,
	`Is it just and right to deny entry to a country when doing so probably means death for the immigrant and their family?`,
	`Should we terraform planets if it means that we may be destroying undiscovered microscopic alien life?`,
	`Does anonymity encourage people to misbehave or does it reveal how people would choose to act all the time if they could?`,
	`What is the most fertile soil for hatred? Fear, ignorance, jealousy, or something else entirely? Is it possible that some people are genetically predisposed to hatred?`,
	`If doing something good for others makes us feel good, can there ever be such a thing as pure altruism?`,
	`What is your definition of evil?`,
	`Do all people have equal value regardless of their actions or is a person’s value based on their actions?`,
	`Why are humans so fascinated by mass murderers if their actions are universally considered evil and vile?`,
	`As people, we feel our moral obligation weaken with physical as well as emotional distance from individuals in need. For example, you’re more likely to help someone dying of hunger at your feet than someone dying of hunger in another country. How does this human trait of morality dependent on distance shape our world?`,
	`If I steal a loaf of bread from you and eat it, when does the bread itself cease to be yours and becomes mine?`,
	`How much effort should an individual put into not offending others?`,
	`If you could start a country from scratch, what would it be like?`,
	`Would a government run with algorithms, A.I., and statistics be better or worse than the government we have now?`,
	`Would the world be a better or worse place if everyone looked the same?`,
	`What causes the most harm in the world, but is completely avoidable?`,
	`How far should governments go to prevent its citizens from causing harm to themselves?`,
	`Do people in wealthier countries have a moral obligation to help those in poorer countries?`,
	`What should the role of a government be, what boundaries and limitations should it have?`,
	`Is poverty in society inevitable?`,
	`How should we measure the productivity of a society?`,
	`What would a utopia be like, how would it function and continue to exist?`,
	`Do you think there will ever be a global government? If a world government did come to power, assuming it wasn’t particularly cruel or evil, would it be a good or bad thing?`,
	`What is the biggest threat to the social contract in our country?`,
	`Is it more or less difficult to be successful in the modern world than it was in the past (10, 50, 100, or 1,000 years ago)?`,
	`Could societies exist without a way to transfer value (i.e. without money or a barter system)?`,
	`What would happen if a maximum income of was implemented?`,
	`What will the economy of wealthy countries look like in 50 to 100 years?`,
	`What do you think the long-term effects of so many people being glued to their screens will be?`,
	`If all humans want the same basic things, why is there so much violence and strife between people?`,
	`Is the human tendency to create groups an overall positive or a negative trait in terms of general human flourishing?`,
	`What would happen to a society in which no one had to work, and everyone was provided enough food/water/shelter healthcare for free?`,
	`Is the cultural trend of individualism and the rejection of collectivism a beneficial or detrimental trend?`,
	`Considering that the technology exists to enable a real democracy, would a true democracy (every single person can vote on every single legislation) be advantageous or detrimental?`,
	`If everyone said what they were actually thinking, what would happen to society?`,
	`What are the benefits and drawbacks of diversity in society?`,
	`Under our government are there any rights that you have but shouldn’t? How about rights you don’t have but should?`,
	`What is the most important right our government allows for?`,
	`Has social media been a net positive or a net negative for our society? Why?`,
	`How would society change if men were able to get pregnant and men and women both had an equal chance of getting pregnant?`,
	`Why have many societies begun to place such a high value on emotions and being emotional?`,
	`Is it right or wrong that everyone seems to be accustomed to the fact that all of humanity and most of the life on Earth could be wiped out at the whim of a handful of people?`,
	`In an ideal government, what should a good citizen provide to their government and what should that government provide that good citizen?`,
	`Should tax payers have the option to explicitly say what they don’t want their tax dollars spent on?`,
	`Can a society exist without laws?`,
	`Will humanity ever be able to escape tribalism and the creation of in and out groups? Should it?`,
	`How much privacy are you willing to sacrifice for safety?`,
	`How would the world change if there was an accurate measure of aptitude?`,
	`Is hierarchy necessary for all successful human communities?`,
	`Is some degree of censorship necessary?`,
	`What are the biggest moral dilemmas your country is facing now?`,
	`Was the agricultural revolution and the explosion of civilizations that came from it an overall good thing for humans or a negative? In other words, would it have been better or worse for people to stay in small tribes?`,
	`What will be/are some of the by-products to society of everyone having the ability to take pictures or a video at any time?`,
	`Does marriage as an institution need to be updated or is it fine how it is?`,
	`If you were given the ability to reform how your country’s leaders were chosen and how they serve, what would you change?`,
	`At what point is a technologically enhanced human not a human anymore?`,
	`Does the modern age make global conspiracies more or less feasible?`,
	`Is technological advancement a net positive or a net negative?`,
	`Is technological progress inevitable as long as humans exist or can it be stopped?`,
	`Is true artificial intelligence possible with our current technology and methods of programming?`,
	`What scientific breakthrough would have the biggest effect on humanity?`,
	`Why did technology progress more slowly in the past than it does now?`,
	`Will we keep leaping to even greater technological and scientific breakthroughs that radically change society, or will the rate of progress slow and humanity’s progress be limited to incremental improvements?`,
	`If a robust and cheap genetic engineering industry existed, would you have your genes edited? If so, what genetic changes would you choose to make? If not, why not?`,
	`Assume that in the future there will be huge leaps in human augmentation. Given a scale from completely human to completely machine, how far would you choose to augment yourself with robotics? What parts would you augment and why?`,
	`If the transporters in Star Trek existed and you used it, your particles would be disassembled and then reassembled, do you die every single time? Are you ever alive at two places at once? Are you ever completely dead?`,
	`Should full access to the internet be a fundamental human right?`,
	`Has the invention of the atomic bomb made the world a more peaceful place?`,
	`Do you think the singularity will occur? If so, what time frame do you think it will happen in?`,
	`If emotions are the product of biochemical reactions, then in the future we will be theoretically able to control them.`,
	`If we could control emotions through technology, should we?`,
	`Is there a limit to what humans can create through technology and science?`,
	`Is cereal soup? Why or why not?`,
	`What is the sexiest and least sexy name?`,
	`What secret conspiracy would you like to start?`,
	`What’s invisible but you wish people could see?`,
	`What’s the weirdest smell you have ever smelled?`,
	`Is a hotdog a sandwich? Why or why not?`,
	`What’s the best Wi-Fi name you’ve seen?`,
	`What’s the most ridiculous fact you know?`,
	`What is something that everyone looks stupid doing? What is the funniest joke you know by heart?`,
	`In 40 years, what will people be nostalgic for?`,
	`What are the unwritten rules of where you work?`,
	`How do you feel about putting pineapple on pizza?`,
	`What part of a kid’s movie completely scarred you?`,
	`What kind of secret society would you like to start?`,
	`If animals could talk, which would be the rudest?`,
	`Toilet paper, over or under?`,
	`What’s the best type of cheese?`,
	`Where is the strangest place you’ve urinated or defecated?`,
	`What’s the best inside joke you’ve been a part of?`,
	`In one sentence, how would you sum up the internet?`,
	`How many chickens would it take to kill an elephant?`,
	`What is the most embarrassing thing you have ever worn?`,
	`What’s the most imaginative insult you can come up with?`,
	`Which body part do you wish you could detach and why?`,
	`What used to be considered trashy but now is very classy?`,
	`What’s the weirdest thing a guest has done at your house?`,
	`What mythical creature would improve the world most if it existed?`,
	`What inanimate object do you wish you could eliminate from existence?`,
	`What is the weirdest thing you have seen in someone else’s home?`,
	`What would be the absolute worst name you could give your child?`,
	`What would be the worst thing for the government to make illegal?`,
	`What are some of the nicknames you have for customers or coworkers?`,
	`If peanut butter wasn’t called peanut butter, what would it be called?`,
	`What movie would be greatly improved if it was made into a musical?`,
	`What is the funniest corporate / business screw up you have heard of?`,
	`What would be the worst “buy one get one free” sale of all time?`,
	`If life were a video game, what would some of the cheat codes be?`,
	`What is the funniest name you have actually heard used in the real world?`,
	`What sport would be the funniest to add a mandatory amount of alcohol to?`,
	`What would be the coolest animal to scale up to the size of a horse?`,
	`What two totally normal things become really weird if you do them back to back?`,
	`What set of items could you buy that would make the cashier the most uncomfortable?`,
	`What would be the creepiest thing you could say while passing a stranger on the street?`,
	`What is something that you just recently realized that you are embarrassed you didn’t realize earlier?`,
	`What are some fun and interesting alternatives to war that countries could settle their differences with?`,
	`What would be the best-worst name for different types of businesses? (dry cleaners, amusement parks, etc.)`,
	`Who do you know that really reminds you of a character in a TV show or movie?`,
	`What would the world be like if it was filled with male and female copies of you?`,
	`What are some things that are okay to occasionally do but definitely not okay to do every day?`,
	`If you were arrested with no explanation, what would your friends and family assume you had done?`,
	`You’re a mad scientist, what scientific experiment would you run if money and ethics weren’t an issue?`,
	`What are some fun ways to answer everyday questions like “how’s it going” or “what do you do”?`,
	`If someone asked to be your apprentice and learn all that you know, what would you teach them?`,
	`If your five-year-old self suddenly found themselves inhabiting your current body, what would your five-year-old self do first?`,
	`First think of a product. Now, what would be the absolute worst brand name for one of those products?`,
	`What movie completely changes its plot when you change one letter in its title? What’s the new movie about?`,
	`If the all the States in the USA were represented by food, what food would each state be represented by?`,
	`What would some fairy tales be like if they took place in the present and included modern technology and culture?`,
	`What is something that is really popular now, but in 5 years everyone will look back on and be embarrassed by?`,
	`What ridiculous and untrue, yet slightly plausible, theories can you come up with for the cause of common ailments like headaches or cavities?`,
	`If you were transported 400 years into the past with no clothes or anything else, how would you prove that you were from the future?`,
	`If you were wrongfully put into an insane asylum, how would you convince them that you’re actually sane and not just pretending to be sane?`,
	`We’ll that’s all the funny questions to ask that we have. But there are a ton of other questions on the site that you might enjoy!`,
	`What fictional character is amazing in their book / show / movie, but would be insufferable if you had to deal with them in mundane everyday situations?`,
	`If you were held at gun point and told that if you didn’t impress them with your dance moves you would be killed, what dance moves would you bust out?`,
	`What would be the hat to end all hats? What could you wear on your head that would make people stop what they are doing and stare in awe and amazement?`,
	`If over time you replace parts on a car, at what point does it stop being the same car you bought? How many parts do you need to replace to make it a new car?`,
	`If you die and find out that everyone gets to choose a twelve-foot by twelve-foot square to stay in alone for eternity without being able to influence or contact the living world, what twelve-foot by twelve-foot square would you choose?`,
	`Where was the most in appropriate / most embarrassing place you’ve farted?`,
];
